name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: make deps

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Format
      run: |
        make fmt
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code is not formatted. Please run 'make fmt'"
          exit 1
        fi

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Run go vet
      run: make vet

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mcp-cli
        path: bin/mcp-cli